"""add_unique_correct_option_constraint

Revision ID: 4f7f3752c181
Revises: 58d323aab1cd
Create Date: 2026-01-30 20:00:29.105139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7f3752c181'
down_revision: Union[str, Sequence[str], None] = '58d323aab1cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_one_correct_option_per_question', 'options', ['question_id'], unique=True, postgresql_where=sa.text('is_correct = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_one_correct_option_per_question', table_name='options', postgresql_where=sa.text('is_correct = true'))
    # ### end Alembic commands ###
