"""add_unique_correct_option_constraint

Revision ID: 5d70663e6ae2
Revises: 4f7f3752c181
Create Date: 2026-01-30 20:00:43.738078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d70663e6ae2'
down_revision: Union[str, Sequence[str], None] = '4f7f3752c181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
