from typing import Optional
from app.domain.entities.task import Task, TaskStatus, TaskPriority
from app.domain.repositories.task_repository import TaskRepository

class CreateTaskUseCase:
    """
    [Feature: Task Management] [Story: create-task] [Ticket: TM-USER-002-BE-T01]
    Orchestrates the creation of a new task.
    """
    def __init__(self, repository: TaskRepository):
        self.repository = repository

    def execute(self, title: str, description: Optional[str] = None, priority: TaskPriority = TaskPriority.media) -> Task:
        task = Task(
            id=None,  # ID will be generated by the database or repository
            title=title,
            description=description,
            status=TaskStatus.pendiente,
            priority=priority
        )
        return self.repository.create(task)
